feat: add draft migration guide
adonisjs/v5-docs pull request #197
Opened 2022-10-26 23:59 UTC by Julien-R44

Just a draft for now to get some initial feedback. I still have some things to add. I'll try to migrate some repo to Vite to see if I miss some elements

2022-10-29 08:38 UTC, RomainLanz requested changes

2022-10-29 08:38 UTC, RomainLanz commented on content/cookbooks/migrating-to-vite.md
> +If you encounter a problem or a missing step in the migration guide, feel free to open an issue or propose a PR as it is more than likely that not all cases are covered.
```suggestion
If you encounter a problem or a missing step in the migration guide, feel free to open an issue or propose a PR, as it is more than likely that only some cases are covered.
```

2022-10-29 08:38 UTC, RomainLanz commented on content/cookbooks/migrating-to-vite.md
> +  - `@adonisjs/vite-plugin-adonis`: Plugin for vite that bridges the gap between AdonisJS and Vite.
```suggestion
  - `vite`
  - `@adonisjs/vite-plugin-adonis`: Plugin for vite bridging the gap between AdonisJS and Vite.
```

2022-10-29 08:38 UTC, RomainLanz commented on content/cookbooks/migrating-to-vite.md
> +You should have a now `vite.config.ts` file at the root of your project with the following content :
```suggestion
You should have a new `vite.config.ts` file at the root of your project with the following content : 
```

2022-10-29 08:38 UTC, RomainLanz commented on content/cookbooks/migrating-to-vite.md
> +Similar to Webpack Encore, you can define multiple entry points. Here, for the sake of simplicity, we only have one entry point named `app`. This entry point can be used in your views by using the we
```suggestion
Similar to Webpack Encore, you can define multiple entry points. Here, for the sake of simplicity, we only have one entry point named `app`. This entry point can be used in your views using the well-known `@entryPointsStyles('app)` and `@entryPointsScripts('app')` helpers tags.
```

2022-10-29 08:38 UTC, RomainLanz commented on content/cookbooks/migrating-to-vite.md
> +Typescript, Css, Postcss, Less, Sass, Tailwind : these tools should just work out of the box. You don't need to configure anything thanks to Vite ⚡.
```suggestion
Typescript, CSS, Postcss, Less, Sass, Tailwind: these tools should work out of the box. You don't need to configure anything thanks to Vite ⚡.
```

2022-10-29 08:38 UTC, RomainLanz commented on content/cookbooks/migrating-to-vite.md
> +Vite only supports ES modules, so you will need to replace any `require()` statements with `import`.
Maybe we should add that at the top of this page (and the Asset Manager doc) with a "warning" box?

2022-10-29 21:45 UTC, Julien-R44 commented
I think we're pretty good with this. We should collect feedback as people migrate to see if we are missing some things

2023-04-30 12:45 UTC, Julien-R44 commented
Closing since the implementation has changed and therefore guide is now outdated

2023-04-30 12:45 UTC, closed without merging